name: cicd
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Deploy
        run: mvn compile jib:build -Djib.to.auth.username=${{ SECRETS.DOCKER_USERNAME }} -Djib.to.auth.password=${{ SECRETS.DOCKER_PASSWORD }}